---
title: "ST2195 Programming for Data Science"
author: "Lee Hin Sing Raymond"
data: November 2021
---

# Practice Assignment 1

### Introduction

This is the first assignment for the course [**ST2195 Programming for Data Science**](https://www.lse.ac.uk/study-at-lse/uolip/Assets/documents/21-22-CIS-Sheets/ST2195-Programming-for-data-science.pdf). R and Python programming will be the main focus of this introductory course.

This is a compulsory 200-course for students who are going for a **BSc Data Science and Business Analytics** degree in the University of London, the academic direction of the degree program is provided by [London School of Economics and Political Science](https://www.lse.ac.uk/) (LSE). The course convenors are Mr [Ioannis Kosmidis](https://www.ikosmidis.com/) and Dr [Kostas Kalogeropoulos](https://www.lse.ac.uk/Statistics/People/Dr-Kostas-Kalogeropoulos).

Throughout the half-year course, there will be a take-home assignment every two weeks to demonstrate what we have learned before. All final works should be uploaded to a GitHub repository for version control.

### Assignment

Create a GitHub repository called “st2195_assignment_1” that includes:

* a README.md file with a short markdown description of this assignment [1 point]

* a folder called “r” with a R-studio project containing an R script that prints all integers between 1 and 10 (including 1 and 10) to screen

* a folder called “python” with a Spyder project containing a Python script that prints all integers between 1 and 10 (including 1 and 10) to screen

* an R Markdown file and a Jupyter notebook with a few introductory markdown comments and cells with the code from parts 2. (R) and 3. (Python) of this assignment. The files should be saved in the corresponding folders. Also, the two html files generated by the R Markdown and Jupyter notebook. [1.5 point per notebook]

All the items described above (i.e., every bullet point) should be committed separately 
to the repository [2 points].